
--------------------------------------------------------

-- Archivo creado  - martes-julio-21-2026
--------------------------------------------------------

--------------------------------------------------------

--  DDL for Sequence SEQ_AUDITORIA
--------------------------------------------------------


   CREATE SEQUENCE  "PROYECTO_BD"."SEQ_AUDITORIA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
--------------------------------------------------------

--  DDL for Sequence SEQ_CLIENTES
--------------------------------------------------------


   CREATE SEQUENCE  "PROYECTO_BD"."SEQ_CLIENTES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
--------------------------------------------------------

--  DDL for Sequence SEQ_DETALLE_VENTA
--------------------------------------------------------


   CREATE SEQUENCE  "PROYECTO_BD"."SEQ_DETALLE_VENTA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
--------------------------------------------------------

--  DDL for Sequence SEQ_PRODUCTOS
--------------------------------------------------------


   CREATE SEQUENCE  "PROYECTO_BD"."SEQ_PRODUCTOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
--------------------------------------------------------

--  DDL for Sequence SEQ_USUARIOS
--------------------------------------------------------


   CREATE SEQUENCE  "PROYECTO_BD"."SEQ_USUARIOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
--------------------------------------------------------

--  DDL for Sequence SEQ_VENTAS
--------------------------------------------------------


   CREATE SEQUENCE  "PROYECTO_BD"."SEQ_VENTAS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
--------------------------------------------------------

--  DDL for Table AUDITORIA_CLIENTES
--------------------------------------------------------


  CREATE TABLE "PROYECTO_BD"."AUDITORIA_CLIENTES" 
   (	"ID_AUDITORIA" NUMBER NOT NULL ENABLE, 
	"ID_CLIENTE" NUMBER NOT NULL ENABLE, 
	"CAMPO_MODIFICADO" VARCHAR2(50) NOT NULL ENABLE, 
	"VALOR_ANTERIOR" VARCHAR2(300), 
	"VALOR_NUEVO" VARCHAR2(300), 
	"FECHA_CAMBIO" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"USUARIO_DB" VARCHAR2(50) DEFAULT USER NOT NULL ENABLE, 
	 CONSTRAINT "PK_AUDITORIA_CLIENTES" PRIMARY KEY ("ID_AUDITORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
--------------------------------------------------------

--  DDL for Table CLIENTES
--------------------------------------------------------


  CREATE TABLE "PROYECTO_BD"."CLIENTES" 
   (	"ID_CLIENTE" NUMBER NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(80) NOT NULL ENABLE, 
	"APELLIDO" VARCHAR2(80) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(150) NOT NULL ENABLE, 
	"TELEFONO" VARCHAR2(20), 
	"DIRECCION" VARCHAR2(200), 
	"ACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"FECHA_CREACION" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"FECHA_MODIFICACION" DATE, 
	 CONSTRAINT "CK_CLIENTES_ACTIVO" CHECK (ACTIVO IN (0,1)) ENABLE, 
	 CONSTRAINT "PK_CLIENTES" PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "UQ_CLIENTES_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
--------------------------------------------------------

--  DDL for Table DETALLE_VENTA
--------------------------------------------------------


  CREATE TABLE "PROYECTO_BD"."DETALLE_VENTA" 
   (	"ID_DETALLE" NUMBER NOT NULL ENABLE, 
	"ID_VENTA" NUMBER NOT NULL ENABLE, 
	"ID_PRODUCTO" NUMBER NOT NULL ENABLE, 
	"CANTIDAD" NUMBER(6,0) NOT NULL ENABLE, 
	"PRECIO_UNITARIO" NUMBER(10,2) NOT NULL ENABLE, 
	"SUBTOTAL" NUMBER(12,2) NOT NULL ENABLE, 
	 CONSTRAINT "CK_DETALLE_CANTIDAD" CHECK (CANTIDAD > 0) ENABLE, 
	 CONSTRAINT "PK_DETALLE_VENTA" PRIMARY KEY ("ID_DETALLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_DETALLE_VENTA" FOREIGN KEY ("ID_VENTA")
	  REFERENCES "PROYECTO_BD"."VENTAS" ("ID_VENTA") ENABLE, 
	 CONSTRAINT "FK_DETALLE_PRODUCTO" FOREIGN KEY ("ID_PRODUCTO")
	  REFERENCES "PROYECTO_BD"."PRODUCTOS" ("ID_PRODUCTO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
--------------------------------------------------------

--  DDL for Table PRODUCTOS
--------------------------------------------------------


  CREATE TABLE "PROYECTO_BD"."PRODUCTOS" 
   (	"ID_PRODUCTO" NUMBER NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(120) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(300), 
	"PRECIO" NUMBER(10,2) NOT NULL ENABLE, 
	"STOCK" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"FECHA_CREACION" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"FECHA_MODIFICACION" DATE, 
	 CONSTRAINT "CK_PRODUCTOS_PRECIO" CHECK (PRECIO >= 0) ENABLE, 
	 CONSTRAINT "CK_PRODUCTOS_STOCK" CHECK (STOCK >= 0) ENABLE, 
	 CONSTRAINT "PK_PRODUCTOS" PRIMARY KEY ("ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
--------------------------------------------------------

--  DDL for Table USUARIOS
--------------------------------------------------------


  CREATE TABLE "PROYECTO_BD"."USUARIOS" 
   (	"ID_USUARIO" NUMBER NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50) NOT NULL ENABLE, 
	"PASSWORD_HASH" VARCHAR2(256) NOT NULL ENABLE, 
	"NOMBRE_COMPLETO" VARCHAR2(150), 
	"ACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"FECHA_REGISTRO" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "CK_USUARIOS_ACTIVO" CHECK (ACTIVO IN (0,1)) ENABLE, 
	 CONSTRAINT "PK_USUARIOS" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "UQ_USUARIOS_USERNAME" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
--------------------------------------------------------

--  DDL for Table VENTAS
--------------------------------------------------------


  CREATE TABLE "PROYECTO_BD"."VENTAS" 
   (	"ID_VENTA" NUMBER NOT NULL ENABLE, 
	"ID_CLIENTE" NUMBER NOT NULL ENABLE, 
	"FECHA_VENTA" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"TOTAL" NUMBER(12,2) DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "PK_VENTAS" PRIMARY KEY ("ID_VENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_VENTAS_CLIENTE" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "PROYECTO_BD"."CLIENTES" ("ID_CLIENTE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
--------------------------------------------------------

--  DDL for View VW_CLIENTES_ACTIVOS
--------------------------------------------------------


  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PROYECTO_BD"."VW_CLIENTES_ACTIVOS" ("ID_CLIENTE", "NOMBRE", "APELLIDO", "EMAIL", "TELEFONO", "DIRECCION", "FECHA_CREACION") AS 
  SELECT ID_CLIENTE, NOMBRE, APELLIDO, EMAIL, TELEFONO, DIRECCION, FECHA_CREACION
FROM CLIENTES
WHERE ACTIVO = 1;
--------------------------------------------------------

--  DDL for View VW_REPORTE_VENTAS_DETALLADO
--------------------------------------------------------


  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PROYECTO_BD"."VW_REPORTE_VENTAS_DETALLADO" ("ID_VENTA", "FECHA_VENTA", "ID_CLIENTE", "CLIENTE", "ID_PRODUCTO", "PRODUCTO", "CANTIDAD", "PRECIO_UNITARIO", "SUBTOTAL", "TOTAL_VENTA") AS 
  SELECT v.ID_VENTA,
       v.FECHA_VENTA,
       c.ID_CLIENTE,
       c.NOMBRE || ' ' || c.APELLIDO   AS CLIENTE,
       p.ID_PRODUCTO,
       p.NOMBRE                        AS PRODUCTO,
       d.CANTIDAD,
       d.PRECIO_UNITARIO,
       d.SUBTOTAL,
       v.TOTAL                         AS TOTAL_VENTA
FROM VENTAS v
JOIN CLIENTES c        ON c.ID_CLIENTE  = v.ID_CLIENTE
JOIN DETALLE_VENTA d   ON d.ID_VENTA    = v.ID_VENTA
JOIN PRODUCTOS p       ON p.ID_PRODUCTO = d.ID_PRODUCTO;
--------------------------------------------------------

--  DDL for View VW_VENTAS_TOTALES_CLIENTE
--------------------------------------------------------


  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PROYECTO_BD"."VW_VENTAS_TOTALES_CLIENTE" ("ID_CLIENTE", "NOMBRE", "APELLIDO", "EMAIL", "NUMERO_VENTAS", "TOTAL_COMPRADO") AS 
  SELECT c.ID_CLIENTE,
       c.NOMBRE,
       c.APELLIDO,
       c.EMAIL,
       COUNT(v.ID_VENTA)            AS NUMERO_VENTAS,
       NVL(SUM(v.TOTAL), 0)         AS TOTAL_COMPRADO
FROM CLIENTES c
LEFT JOIN VENTAS v ON v.ID_CLIENTE = c.ID_CLIENTE
GROUP BY c.ID_CLIENTE, c.NOMBRE, c.APELLIDO, c.EMAIL
REM INSERTING into PROYECTO_BD.AUDITORIA_CLIENTES
SET DEFINE OFF;
Insert into PROYECTO_BD.AUDITORIA_CLIENTES (ID_AUDITORIA,ID_CLIENTE,CAMPO_MODIFICADO,VALOR_ANTERIOR,VALOR_NUEVO,FECHA_CAMBIO,USUARIO_DB) values ('1','1','DIRECCION','Quito, Ecuador','Guayaquil, Ecuador',to_date('21/07/2026','DD/MM/RRRR'),'PROYECTO_BD');
REM INSERTING into PROYECTO_BD.CLIENTES
SET DEFINE OFF;
Insert into PROYECTO_BD.CLIENTES (ID_CLIENTE,NOMBRE,APELLIDO,EMAIL,TELEFONO,DIRECCION,ACTIVO,FECHA_CREACION,FECHA_MODIFICACION) values ('1','Maria','Perez','maria.perez@correo.com','0991234567','Guayaquil, Ecuador','1',to_date('21/07/2026','DD/MM/RRRR'),to_date('21/07/2026','DD/MM/RRRR'));
Insert into PROYECTO_BD.CLIENTES (ID_CLIENTE,NOMBRE,APELLIDO,EMAIL,TELEFONO,DIRECCION,ACTIVO,FECHA_CREACION,FECHA_MODIFICACION) values ('2','Carlos','Suarez','carlos.suarez@correo.com','0987654321','Sangolqui, Ecuador','1',to_date('21/07/2026','DD/MM/RRRR'),null);
Insert into PROYECTO_BD.CLIENTES (ID_CLIENTE,NOMBRE,APELLIDO,EMAIL,TELEFONO,DIRECCION,ACTIVO,FECHA_CREACION,FECHA_MODIFICACION) values ('3','Lucia','Ramirez','lucia.ramirez@correo.com','0978889900','Ambato, Ecuador','1',to_date('21/07/2026','DD/MM/RRRR'),null);
REM INSERTING into PROYECTO_BD.DETALLE_VENTA
SET DEFINE OFF;
Insert into PROYECTO_BD.DETALLE_VENTA (ID_DETALLE,ID_VENTA,ID_PRODUCTO,CANTIDAD,PRECIO_UNITARIO,SUBTOTAL) values ('1','1','1','2','45,99','91,98');
Insert into PROYECTO_BD.DETALLE_VENTA (ID_DETALLE,ID_VENTA,ID_PRODUCTO,CANTIDAD,PRECIO_UNITARIO,SUBTOTAL) values ('2','2','3','1','159','159');
REM INSERTING into PROYECTO_BD.PRODUCTOS
SET DEFINE OFF;
Insert into PROYECTO_BD.PRODUCTOS (ID_PRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,FECHA_CREACION,FECHA_MODIFICACION) values ('1','Teclado Mecanico','Teclado mecanico retroiluminado','45,99','30',to_date('21/07/2026','DD/MM/RRRR'),null);
Insert into PROYECTO_BD.PRODUCTOS (ID_PRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,FECHA_CREACION,FECHA_MODIFICACION) values ('2','Mouse Inalambrico','Mouse ergonomico inalambrico','19,5','50',to_date('21/07/2026','DD/MM/RRRR'),null);
Insert into PROYECTO_BD.PRODUCTOS (ID_PRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,FECHA_CREACION,FECHA_MODIFICACION) values ('3','Monitor 24 pulgadas','Monitor Full HD 24"','159','15',to_date('21/07/2026','DD/MM/RRRR'),null);
REM INSERTING into PROYECTO_BD.USUARIOS
SET DEFINE OFF;
Insert into PROYECTO_BD.USUARIOS (ID_USUARIO,USERNAME,PASSWORD_HASH,NOMBRE_COMPLETO,ACTIVO,FECHA_REGISTRO) values ('1','admin','3B612C75A7B5048A435FB6EC81E52FF92D6D795A8B5A9C17070F6A63C97A53B2','Administrador del Sistema','1',to_date('21/07/2026','DD/MM/RRRR'));
Insert into PROYECTO_BD.USUARIOS (ID_USUARIO,USERNAME,PASSWORD_HASH,NOMBRE_COMPLETO,ACTIVO,FECHA_REGISTRO) values ('2','m3nm4','C0F9DD70BC1E756102407DB97D747451A7E19B3A836C5B24C733FA47D6E3C24E','Miguel Angel','1',to_date('21/07/2026','DD/MM/RRRR'));
REM INSERTING into PROYECTO_BD.VENTAS
SET DEFINE OFF;
Insert into PROYECTO_BD.VENTAS (ID_VENTA,ID_CLIENTE,FECHA_VENTA,TOTAL) values ('1','1',to_date('11/07/2026','DD/MM/RRRR'),'91,98');
Insert into PROYECTO_BD.VENTAS (ID_VENTA,ID_CLIENTE,FECHA_VENTA,TOTAL) values ('2','2',to_date('18/07/2026','DD/MM/RRRR'),'159');
--------------------------------------------------------

--  DDL for Index UQ_USUARIOS_USERNAME
--------------------------------------------------------


  CREATE UNIQUE INDEX "PROYECTO_BD"."UQ_USUARIOS_USERNAME" ON "PROYECTO_BD"."USUARIOS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
--------------------------------------------------------

--  DDL for Index IX_VENTAS_CLIENTE_FECHA
--------------------------------------------------------


  CREATE INDEX "PROYECTO_BD"."IX_VENTAS_CLIENTE_FECHA" ON "PROYECTO_BD"."VENTAS" ("ID_CLIENTE", "FECHA_VENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
--------------------------------------------------------

--  DDL for Index IX_CLIENTES_NOMBRE_APELLIDO
--------------------------------------------------------


  CREATE INDEX "PROYECTO_BD"."IX_CLIENTES_NOMBRE_APELLIDO" ON "PROYECTO_BD"."CLIENTES" ("NOMBRE", "APELLIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
--------------------------------------------------------

--  DDL for Index IX_DETALLE_VENTA_VENTA
--------------------------------------------------------


  CREATE INDEX "PROYECTO_BD"."IX_DETALLE_VENTA_VENTA" ON "PROYECTO_BD"."DETALLE_VENTA" ("ID_VENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
--------------------------------------------------------

--  DDL for Index PK_CLIENTES
--------------------------------------------------------


  CREATE UNIQUE INDEX "PROYECTO_BD"."PK_CLIENTES" ON "PROYECTO_BD"."CLIENTES" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
--------------------------------------------------------

--  DDL for Index PK_AUDITORIA_CLIENTES
--------------------------------------------------------


  CREATE UNIQUE INDEX "PROYECTO_BD"."PK_AUDITORIA_CLIENTES" ON "PROYECTO_BD"."AUDITORIA_CLIENTES" ("ID_AUDITORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
--------------------------------------------------------

--  DDL for Index PK_VENTAS
--------------------------------------------------------


  CREATE UNIQUE INDEX "PROYECTO_BD"."PK_VENTAS" ON "PROYECTO_BD"."VENTAS" ("ID_VENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
--------------------------------------------------------

--  DDL for Index UQ_CLIENTES_EMAIL
--------------------------------------------------------


  CREATE UNIQUE INDEX "PROYECTO_BD"."UQ_CLIENTES_EMAIL" ON "PROYECTO_BD"."CLIENTES" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
--------------------------------------------------------

--  DDL for Index IX_VENTAS_FECHA
--------------------------------------------------------


  CREATE INDEX "PROYECTO_BD"."IX_VENTAS_FECHA" ON "PROYECTO_BD"."VENTAS" ("FECHA_VENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
--------------------------------------------------------

--  DDL for Index PK_USUARIOS
--------------------------------------------------------


  CREATE UNIQUE INDEX "PROYECTO_BD"."PK_USUARIOS" ON "PROYECTO_BD"."USUARIOS" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
--------------------------------------------------------

--  DDL for Index PK_PRODUCTOS
--------------------------------------------------------


  CREATE UNIQUE INDEX "PROYECTO_BD"."PK_PRODUCTOS" ON "PROYECTO_BD"."PRODUCTOS" ("ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
--------------------------------------------------------

--  DDL for Index PK_DETALLE_VENTA
--------------------------------------------------------


  CREATE UNIQUE INDEX "PROYECTO_BD"."PK_DETALLE_VENTA" ON "PROYECTO_BD"."DETALLE_VENTA" ("ID_DETALLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
--------------------------------------------------------

--  DDL for Index IX_AUDITORIA_CLIENTE
--------------------------------------------------------


  CREATE INDEX "PROYECTO_BD"."IX_AUDITORIA_CLIENTE" ON "PROYECTO_BD"."AUDITORIA_CLIENTES" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
--------------------------------------------------------

--  DDL for Index IX_DETALLE_VENTA_PRODUCTO
--------------------------------------------------------


  CREATE INDEX "PROYECTO_BD"."IX_DETALLE_VENTA_PRODUCTO" ON "PROYECTO_BD"."DETALLE_VENTA" ("ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
--------------------------------------------------------

--  DDL for Trigger TRG_CLIENTES_AU
--------------------------------------------------------


  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO_BD"."TRG_CLIENTES_AU" 
AFTER UPDATE ON CLIENTES
FOR EACH ROW
BEGIN
    IF :OLD.NOMBRE != :NEW.NOMBRE THEN
        INSERT INTO AUDITORIA_CLIENTES (ID_AUDITORIA, ID_CLIENTE, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO)
        VALUES (SEQ_AUDITORIA.NEXTVAL, :NEW.ID_CLIENTE, 'NOMBRE', :OLD.NOMBRE, :NEW.NOMBRE);
    END IF;

    IF :OLD.APELLIDO != :NEW.APELLIDO THEN
        INSERT INTO AUDITORIA_CLIENTES (ID_AUDITORIA, ID_CLIENTE, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO)
        VALUES (SEQ_AUDITORIA.NEXTVAL, :NEW.ID_CLIENTE, 'APELLIDO', :OLD.APELLIDO, :NEW.APELLIDO);
    END IF;

    IF :OLD.EMAIL != :NEW.EMAIL THEN
        INSERT INTO AUDITORIA_CLIENTES (ID_AUDITORIA, ID_CLIENTE, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO)
        VALUES (SEQ_AUDITORIA.NEXTVAL, :NEW.ID_CLIENTE, 'EMAIL', :OLD.EMAIL, :NEW.EMAIL);
    END IF;

    IF NVL(:OLD.TELEFONO,'-') != NVL(:NEW.TELEFONO,'-') THEN
        INSERT INTO AUDITORIA_CLIENTES (ID_AUDITORIA, ID_CLIENTE, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO)
        VALUES (SEQ_AUDITORIA.NEXTVAL, :NEW.ID_CLIENTE, 'TELEFONO', :OLD.TELEFONO, :NEW.TELEFONO);
    END IF;

    IF NVL(:OLD.DIRECCION,'-') != NVL(:NEW.DIRECCION,'-') THEN
        INSERT INTO AUDITORIA_CLIENTES (ID_AUDITORIA, ID_CLIENTE, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO)
        VALUES (SEQ_AUDITORIA.NEXTVAL, :NEW.ID_CLIENTE, 'DIRECCION', :OLD.DIRECCION, :NEW.DIRECCION);
    END IF;
END TRG_CLIENTES_AU;

ALTER TRIGGER "PROYECTO_BD"."TRG_CLIENTES_AU" ENABLE;
--------------------------------------------------------

--  DDL for Trigger TRG_CLIENTES_BD
--------------------------------------------------------


  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO_BD"."TRG_CLIENTES_BD" 
BEFORE DELETE ON CLIENTES
FOR EACH ROW
DECLARE
    v_num_ventas NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_num_ventas FROM VENTAS WHERE ID_CLIENTE = :OLD.ID_CLIENTE;

    IF v_num_ventas > 0 THEN
        RAISE_APPLICATION_ERROR(-20003,
            'No se puede eliminar el cliente ' || :OLD.ID_CLIENTE ||
            ': tiene ' || v_num_ventas || ' venta(s) asociada(s).');
    END IF;
END TRG_CLIENTES_BD;

ALTER TRIGGER "PROYECTO_BD"."TRG_CLIENTES_BD" ENABLE;
--------------------------------------------------------

--  DDL for Trigger TRG_CLIENTES_BI
--------------------------------------------------------


  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO_BD"."TRG_CLIENTES_BI" 
BEFORE INSERT ON CLIENTES
FOR EACH ROW
BEGIN
    -- Validacion basica de formato de correo
    IF :NEW.EMAIL IS NULL OR INSTR(:NEW.EMAIL, '@') = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'El email del cliente no tiene un formato valido.');
    END IF;

    -- Nombre y apellido obligatorios y no vacios
    IF TRIM(:NEW.NOMBRE) IS NULL OR TRIM(:NEW.APELLIDO) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20002, 'El nombre y el apellido del cliente son obligatorios.');
    END IF;

    -- Normaliza el email a minusculas y asigna fecha de creacion
    :NEW.EMAIL := LOWER(:NEW.EMAIL);
    :NEW.FECHA_CREACION := SYSDATE;
END TRG_CLIENTES_BI;

ALTER TRIGGER "PROYECTO_BD"."TRG_CLIENTES_BI" ENABLE;
--------------------------------------------------------

--  DDL for Trigger TRG_CLIENTES_BU_FECHA
--------------------------------------------------------


  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO_BD"."TRG_CLIENTES_BU_FECHA" 
BEFORE UPDATE ON CLIENTES
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSDATE;
END TRG_CLIENTES_BU_FECHA;

ALTER TRIGGER "PROYECTO_BD"."TRG_CLIENTES_BU_FECHA" ENABLE;
--------------------------------------------------------

--  DDL for Trigger TRG_PRODUCTOS_AU_FECHA
--------------------------------------------------------


  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO_BD"."TRG_PRODUCTOS_AU_FECHA" 
AFTER INSERT OR UPDATE ON PRODUCTOS
FOR EACH ROW
DECLARE
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    UPDATE PRODUCTOS
       SET FECHA_MODIFICACION = SYSDATE
     WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;
    COMMIT;
END TRG_PRODUCTOS_AU_FECHA;

ALTER TRIGGER "PROYECTO_BD"."TRG_PRODUCTOS_AU_FECHA" ENABLE;
--------------------------------------------------------

--  DDL for Procedure SP_CLIENTE_DELETE
--------------------------------------------------------

set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO_BD"."SP_CLIENTE_DELETE" (
    p_id_cliente  IN  NUMBER,
    o_estado      OUT VARCHAR2
) AS
BEGIN
    DELETE FROM CLIENTES WHERE ID_CLIENTE = p_id_cliente;
    COMMIT;
    o_estado := 'OK';
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        o_estado := 'ERROR: ' || SQLERRM;  -- captura el error lanzado por el trigger BEFORE DELETE
END SP_CLIENTE_DELETE;
--------------------------------------------------------

--  DDL for Procedure SP_CLIENTE_INSERT
--------------------------------------------------------

set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO_BD"."SP_CLIENTE_INSERT" (
    p_nombre      IN  VARCHAR2,
    p_apellido    IN  VARCHAR2,
    p_email       IN  VARCHAR2,
    p_telefono    IN  VARCHAR2,
    p_direccion   IN  VARCHAR2,
    o_id_cliente  OUT NUMBER,
    o_estado      OUT VARCHAR2
) AS
BEGIN
    o_id_cliente := SEQ_CLIENTES.NEXTVAL;
    INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, EMAIL, TELEFONO, DIRECCION)
    VALUES (o_id_cliente, p_nombre, p_apellido, p_email, p_telefono, p_direccion);
    COMMIT;
    o_estado := 'OK';
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        o_estado := 'ERROR: ' || SQLERRM;
END SP_CLIENTE_INSERT;
--------------------------------------------------------

--  DDL for Procedure SP_CLIENTE_SELECT_ALL
--------------------------------------------------------

set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO_BD"."SP_CLIENTE_SELECT_ALL" (
    o_cursor  OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN o_cursor FOR
        SELECT ID_CLIENTE, NOMBRE, APELLIDO, EMAIL, TELEFONO, DIRECCION,
               ACTIVO, FECHA_CREACION, FECHA_MODIFICACION
          FROM CLIENTES
         ORDER BY ID_CLIENTE;
END SP_CLIENTE_SELECT_ALL;
--------------------------------------------------------

--  DDL for Procedure SP_CLIENTE_SELECT_BY_ID
--------------------------------------------------------

set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO_BD"."SP_CLIENTE_SELECT_BY_ID" (
    p_id_cliente IN  NUMBER,
    o_cursor     OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN o_cursor FOR
        SELECT ID_CLIENTE, NOMBRE, APELLIDO, EMAIL, TELEFONO, DIRECCION,
               ACTIVO, FECHA_CREACION, FECHA_MODIFICACION
          FROM CLIENTES
         WHERE ID_CLIENTE = p_id_cliente;
END SP_CLIENTE_SELECT_BY_ID;
--------------------------------------------------------

--  DDL for Procedure SP_CLIENTE_UPDATE
--------------------------------------------------------

set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO_BD"."SP_CLIENTE_UPDATE" (
    p_id_cliente  IN  NUMBER,
    p_nombre      IN  VARCHAR2,
    p_apellido    IN  VARCHAR2,
    p_email       IN  VARCHAR2,
    p_telefono    IN  VARCHAR2,
    p_direccion   IN  VARCHAR2,
    o_estado      OUT VARCHAR2
) AS
BEGIN
    UPDATE CLIENTES
       SET NOMBRE = p_nombre,
           APELLIDO = p_apellido,
           EMAIL = p_email,
           TELEFONO = p_telefono,
           DIRECCION = p_direccion
     WHERE ID_CLIENTE = p_id_cliente;

    IF SQL%ROWCOUNT = 0 THEN
        o_estado := 'NO_ENCONTRADO';
    ELSE
        COMMIT;
        o_estado := 'OK';
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        o_estado := 'ERROR: ' || SQLERRM;
END SP_CLIENTE_UPDATE;
--------------------------------------------------------

--  DDL for Procedure SP_LOGIN
--------------------------------------------------------

set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO_BD"."SP_LOGIN" (
    p_username     IN  VARCHAR2,
    p_password     IN  VARCHAR2,
    o_estado       OUT VARCHAR2,
    o_id_usuario   OUT NUMBER,
    o_nombre       OUT VARCHAR2
) AS
    v_hash          VARCHAR2(256);
    v_hash_input    VARCHAR2(256);
    v_activo        NUMBER;
    v_id            NUMBER;
    v_nombre        VARCHAR2(150);
BEGIN
    SELECT PASSWORD_HASH, ACTIVO, ID_USUARIO, NOMBRE_COMPLETO
      INTO v_hash, v_activo, v_id, v_nombre
      FROM USUARIOS
     WHERE UPPER(USERNAME) = UPPER(p_username);

    SELECT STANDARD_HASH(p_password, 'SHA256') INTO v_hash_input FROM DUAL;

    IF v_hash != v_hash_input THEN
        o_estado := 'CREDENCIALES_INVALIDAS';
        o_id_usuario := NULL;
        o_nombre := NULL;
    ELSIF v_activo = 0 THEN
        o_estado := 'INACTIVO';
        o_id_usuario := NULL;
        o_nombre := NULL;
    ELSE
        o_estado := 'OK';
        o_id_usuario := v_id;
        o_nombre := v_nombre;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        o_estado := 'CREDENCIALES_INVALIDAS';
        o_id_usuario := NULL;
        o_nombre := NULL;
END SP_LOGIN;
--------------------------------------------------------

--  DDL for Procedure SP_REGISTRO_USUARIO
--------------------------------------------------------

set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO_BD"."SP_REGISTRO_USUARIO" (
    p_username    IN  VARCHAR2,
    p_password    IN  VARCHAR2,
    p_nombre      IN  VARCHAR2,
    o_estado      OUT VARCHAR2
) AS
    v_existe      NUMBER;
    v_hash_input  VARCHAR2(256);
BEGIN
    SELECT COUNT(*) INTO v_existe FROM USUARIOS WHERE UPPER(USERNAME) = UPPER(p_username);

    IF v_existe > 0 THEN
        o_estado := 'USUARIO_DUPLICADO';
        RETURN;
    END IF;

    SELECT STANDARD_HASH(p_password, 'SHA256') INTO v_hash_input FROM DUAL;

    INSERT INTO USUARIOS (ID_USUARIO, USERNAME, PASSWORD_HASH, NOMBRE_COMPLETO, ACTIVO)
    VALUES (SEQ_USUARIOS.NEXTVAL, p_username, v_hash_input, p_nombre, 1);

    COMMIT;
    o_estado := 'OK';
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        o_estado := 'ERROR: ' || SQLERRM;
END SP_REGISTRO_USUARIO;
--------------------------------------------------------

--  DDL for Procedure SP_VENTAS_RANGO_FECHAS
--------------------------------------------------------

set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO_BD"."SP_VENTAS_RANGO_FECHAS" (
    p_fecha_inicio  IN  DATE,
    p_fecha_fin     IN  DATE,
    o_cursor        OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN o_cursor FOR
        SELECT v.ID_VENTA, v.FECHA_VENTA, c.NOMBRE || ' ' || c.APELLIDO AS CLIENTE, v.TOTAL
          FROM VENTAS v
          JOIN CLIENTES c ON c.ID_CLIENTE = v.ID_CLIENTE
         WHERE TRUNC(v.FECHA_VENTA) BETWEEN TRUNC(p_fecha_inicio) AND TRUNC(p_fecha_fin)
         ORDER BY v.FECHA_VENTA;
END SP_VENTAS_RANGO_FECHAS;
--------------------------------------------------------

--  DDL for Procedure SP_VENTAS_TOTALES_CLIENTE
--------------------------------------------------------

set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO_BD"."SP_VENTAS_TOTALES_CLIENTE" (
    p_id_cliente   IN  NUMBER,
    o_total        OUT NUMBER,
    o_num_ventas   OUT NUMBER
) AS
BEGIN
    SELECT NVL(SUM(TOTAL), 0), COUNT(*)
      INTO o_total, o_num_ventas
      FROM VENTAS
     WHERE ID_CLIENTE = p_id_cliente;
END SP_VENTAS_TOTALES_CLIENTE;
--------------------------------------------------------

--  Constraints for Table DETALLE_VENTA
--------------------------------------------------------


  ALTER TABLE "PROYECTO_BD"."DETALLE_VENTA" MODIFY ("ID_DETALLE" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."DETALLE_VENTA" MODIFY ("ID_VENTA" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."DETALLE_VENTA" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."DETALLE_VENTA" MODIFY ("CANTIDAD" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."DETALLE_VENTA" MODIFY ("PRECIO_UNITARIO" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."DETALLE_VENTA" MODIFY ("SUBTOTAL" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."DETALLE_VENTA" ADD CONSTRAINT "CK_DETALLE_CANTIDAD" CHECK (CANTIDAD > 0) ENABLE
  ALTER TABLE "PROYECTO_BD"."DETALLE_VENTA" ADD CONSTRAINT "PK_DETALLE_VENTA" PRIMARY KEY ("ID_DETALLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
--------------------------------------------------------

--  Constraints for Table USUARIOS
--------------------------------------------------------


  ALTER TABLE "PROYECTO_BD"."USUARIOS" MODIFY ("ID_USUARIO" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."USUARIOS" MODIFY ("USERNAME" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."USUARIOS" MODIFY ("PASSWORD_HASH" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."USUARIOS" MODIFY ("ACTIVO" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."USUARIOS" MODIFY ("FECHA_REGISTRO" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."USUARIOS" ADD CONSTRAINT "CK_USUARIOS_ACTIVO" CHECK (ACTIVO IN (0,1)) ENABLE
  ALTER TABLE "PROYECTO_BD"."USUARIOS" ADD CONSTRAINT "PK_USUARIOS" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
  ALTER TABLE "PROYECTO_BD"."USUARIOS" ADD CONSTRAINT "UQ_USUARIOS_USERNAME" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
--------------------------------------------------------

--  Constraints for Table PRODUCTOS
--------------------------------------------------------


  ALTER TABLE "PROYECTO_BD"."PRODUCTOS" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."PRODUCTOS" MODIFY ("NOMBRE" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."PRODUCTOS" MODIFY ("PRECIO" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."PRODUCTOS" MODIFY ("STOCK" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."PRODUCTOS" MODIFY ("FECHA_CREACION" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."PRODUCTOS" ADD CONSTRAINT "CK_PRODUCTOS_PRECIO" CHECK (PRECIO >= 0) ENABLE
  ALTER TABLE "PROYECTO_BD"."PRODUCTOS" ADD CONSTRAINT "CK_PRODUCTOS_STOCK" CHECK (STOCK >= 0) ENABLE
  ALTER TABLE "PROYECTO_BD"."PRODUCTOS" ADD CONSTRAINT "PK_PRODUCTOS" PRIMARY KEY ("ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
--------------------------------------------------------

--  Constraints for Table CLIENTES
--------------------------------------------------------


  ALTER TABLE "PROYECTO_BD"."CLIENTES" MODIFY ("ID_CLIENTE" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."CLIENTES" MODIFY ("NOMBRE" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."CLIENTES" MODIFY ("APELLIDO" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."CLIENTES" MODIFY ("EMAIL" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."CLIENTES" MODIFY ("ACTIVO" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."CLIENTES" MODIFY ("FECHA_CREACION" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."CLIENTES" ADD CONSTRAINT "CK_CLIENTES_ACTIVO" CHECK (ACTIVO IN (0,1)) ENABLE
  ALTER TABLE "PROYECTO_BD"."CLIENTES" ADD CONSTRAINT "PK_CLIENTES" PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
  ALTER TABLE "PROYECTO_BD"."CLIENTES" ADD CONSTRAINT "UQ_CLIENTES_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
--------------------------------------------------------

--  Constraints for Table VENTAS
--------------------------------------------------------


  ALTER TABLE "PROYECTO_BD"."VENTAS" MODIFY ("ID_VENTA" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."VENTAS" MODIFY ("ID_CLIENTE" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."VENTAS" MODIFY ("FECHA_VENTA" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."VENTAS" MODIFY ("TOTAL" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."VENTAS" ADD CONSTRAINT "PK_VENTAS" PRIMARY KEY ("ID_VENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
--------------------------------------------------------

--  Constraints for Table AUDITORIA_CLIENTES
--------------------------------------------------------


  ALTER TABLE "PROYECTO_BD"."AUDITORIA_CLIENTES" MODIFY ("ID_AUDITORIA" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."AUDITORIA_CLIENTES" MODIFY ("ID_CLIENTE" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."AUDITORIA_CLIENTES" MODIFY ("CAMPO_MODIFICADO" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."AUDITORIA_CLIENTES" MODIFY ("FECHA_CAMBIO" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."AUDITORIA_CLIENTES" MODIFY ("USUARIO_DB" NOT NULL ENABLE)
  ALTER TABLE "PROYECTO_BD"."AUDITORIA_CLIENTES" ADD CONSTRAINT "PK_AUDITORIA_CLIENTES" PRIMARY KEY ("ID_AUDITORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
--------------------------------------------------------

--  Ref Constraints for Table DETALLE_VENTA
--------------------------------------------------------


  ALTER TABLE "PROYECTO_BD"."DETALLE_VENTA" ADD CONSTRAINT "FK_DETALLE_VENTA" FOREIGN KEY ("ID_VENTA")
	  REFERENCES "PROYECTO_BD"."VENTAS" ("ID_VENTA") ENABLE
  ALTER TABLE "PROYECTO_BD"."DETALLE_VENTA" ADD CONSTRAINT "FK_DETALLE_PRODUCTO" FOREIGN KEY ("ID_PRODUCTO")
	  REFERENCES "PROYECTO_BD"."PRODUCTOS" ("ID_PRODUCTO") ENABLE
--------------------------------------------------------

--  Ref Constraints for Table VENTAS
--------------------------------------------------------


  ALTER TABLE "PROYECTO_BD"."VENTAS" ADD CONSTRAINT "FK_VENTAS_CLIENTE" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "PROYECTO_BD"."CLIENTES" ("ID_CLIENTE") ENABLE